# specific pronunciations for Italian ingredients to insert in our lexicon

(lex.add.entry '("radicchio" nn (((r @) 0) ((d ii) 1) ((k iy) 0) ((ou) 0))))
(lex.add.entry '("porcini" nns (((p @ r) 0) ((t sh ii) 1) ((n iy) 0))))
(lex.add.entry '("pesto" nn (((p e) 1) ((s t ou) 0))))
(lex.add.entry '("halloumi" nn (((h @) 0) ((l uu) 1) ((m iy) 0))))
(lex.add.entry '("fraiche" nn (((f r e sh) 1))))
(lex.add.entry '("pecorino" nn (((p @) 0) ((k oo) 0) ((r ii) 1) (( n ou) 0))))
(lex.add.entry '("ciabatta" nn (((t sh @) 0) ((b a) 1) ((t @) 0))))
(lex.add.entry '("crostini" nns (((k r oo) 0) ((s t ii) 1) ((n iy) 0))))
(lex.add.entry '("linguine" nns (((l @ n) 0) ((g w ii) 1) ((n iy) 0))))
(lex.add.entry '("frittata" nn (((f r iy) 0) ((t aa) 1) ((t @) 0))))
(lex.add.entry '("bruschetta" nn (((b r u) 0) ((s k e) 1) ((t @) 0))))
(lex.add.entry '("tagliatelle" nns (((t a) 0) ((l y @) 0) ((t e) 1) (( l iy) 0))))
(lex.add.entry '("masala" nn (((m @) 0) ((s aa) 1) ((l @) 0))))
(lex.add.entry '("tahini" nn (((t a) 0) ((h ii) 1) ((n iy) 0))))
(lex.add.entry '("cannellini" nns (((k a) 0) ((n e) 0) ((l ii) 1) (( n iy) 0))))
(lex.add.entry '("pancetta" nn (((p a n) 0) ((t sh e) 1) ((t @) 0))))
(lex.add.entry '("ragù" nn (((r a) 0) ((g uu) 1))))
(lex.add.entry '("tortellini" nns (((t oo r) 0) ((t e) 0) ((l ii) 1) (( n iy) 0))))
(lex.add.entry '("limoncello" nn (((l iy) 0) ((m @ n) 0) ((t sh e) 1) (( l ou) 0))))
